### PR TITLE
DAVE support

### LINKED ISSUE #293: E2EE/DAVE protocol required
**Songbird version:** 0.5

**Rust version (`rustc -V`):** rustc 1.91.1

**Serenity/Twilight version:** 0.12

**Description:**

When attempting to connect to a voice channel discord returns the error "E2EE/DAVE protocol required"

**Steps to reproduce:**
Get a songbird manager and attempt to join a voice channel using the join method

### PR DESCRIPTION
**Pull request by beer-psi**
Closes #293

Sending voice packets now mostly works.

Receiving is not very heavily tested, and there are a bunch of annoyances:
- ~~Passthrough (unencrypted) voice packets will still go into the decryption code path, so you will get error logs like:~~
```
ERROR davey::cryptor::frame_processors: no magic marker
```
- ~~The UDP receiving task is separate from the gateway task, so decrypting the first few packets *will* fail because the key ratchets haven't been set up yet. This should probably be fixed with a buffer?~~ Packets that are received before the key ratchets are set up are silently dropped.
- `SpeakingStateUpdate` events are apparently not fired consistently

~~The PR is still unreviewed, but~~ if your bot needs this it's been tested and working on a few bots. If you use `serenity-next`, you may want to depend on jtscuba's fork of this PR instead, which depends on `serenity-next`: https://github.com/jtscuba/songbird/tree/davey

## TODO
- [x] `serenity-voice-model` will need to be updated on crates.io to add the missing `dave_protocol_version` field in `SessionDescription`.
- [ ] Add a way to retrieve the voice privacy code and the verification codes (e.g. `Call::voice_privacy_code`?)

### CODE REVIEW

**Comment by beer-psi** [comment]
I'm not sure how I can surface the voice privacy code up to the `Driver` interface in the existing architecture. Could I add a new `CoreEvent::VoicePrivacyCode` or something of that sort and then emit the event when a DAVE transition is executed (which is when the code is changed)?

**Comment by tktcorporation** [comment]
Thanks for the great work on this! I was able to get my library working by pointing to your fork in the meantime. I may not be in a position to contribute much directly, but please let me know if there’s anything I can do to help move this forward!

**Comment by tdgroot** [comment]
Works for me! 😃

**Comment by LukeZurg22** [comment]
By gum, please merge this.

File: src/driver/tasks/ws.rs [hunk 1]
```diff
@@ -38,6 +50,11 @@ pub(crate) struct AuxNetwork {
     attempt_idx: usize,
     info: ConnectionInfo,
 
+    dave_session: Arc<RwLock<Option<davey::DaveSession>>>,
+    dave_protocol_version: Arc<AtomicU16>,
```
Comment (Erk-) [inline src/driver/tasks/ws.rs:60]: ~~This does not need to be atomic~~

**Review by Erk- — CHANGES_REQUESTED** [review]
The changes looks good, ~~I have the comment about the unnecessary (as far as I can tell) atomic~~ (I was wrong there) and then there is some warning of unused values you get when you for example build the twilight example that needs to be cleaned up, but other than that it looks good.

**Comment by Siydge** [comment]
Tested, works great for me, no issues, tested with following override for others in need

```
[patch.crates-io]
songbird = { git = "https://github.com/beerpsi-forks/songbird", branch = "davey" }
```

**Review by Erk- — APPROVED** [review]

**Comment by Achilleees** [comment]
Thanks for this guys. Tested and works great! Looking forward to the merge.

**Comment by krywicki** [comment]
Ran in to trouble with DAVE protocol on my sound bot. I've added this as a songbird patch and tested it. It  works great!  :raised_hands:

File: src/driver/connection/mod.rs [hunk 2]
```diff
@@ -358,9 +375,38 @@ async fn init_cipher(
...
-                return mode
-                    .cipher_from_key(&desc.secret_key)
-                    .map_err(|_| Error::CryptoInvalidLength);
+                let dave_session =
+                    if let Some(version) = NonZeroU16::new(desc.dave_protocol_version) {
+                        let mut session = davey::DaveSession::new(
+                            version,
+                            info.user_id.0.into(),
+                            info.channel_id
+                                .expect("channel ID must be set in connection info")
```
Comment (tazz4843) [inline src/driver/connection/mod.rs:384]: If we need channel ID to establish a connection we should update this type to remove the option entirely and remove the doc string saying "channel ID is not needed" https://github.com/serenity-rs/songbird/blob/e8c134664ba4063db5a5f06d5417182d2c7514f6/src/info.rs#L106-L110

File: src/driver/tasks/ws.rs [hunk 3]
```diff
@@ -38,6 +56,11 @@ pub(crate) struct AuxNetwork {
     attempt_idx: usize,
     info: ConnectionInfo,
 
+    dave_session: Arc<RwLock<Option<davey::DaveSession>>>,
```
Comment (tazz4843) [inline src/driver/tasks/ws.rs:59]: Does this need to be a tokio `RwLock`? None of the methods on `DaveSession` are asynchronous, and as far as I can tell a lock is never held over an await point (if it is and I missed one, disregard this comment). For performance reasons we should prefer standard synchronous `RwLock`s if possible.

**Review by tazz4843 — CHANGES_REQUESTED** [review]

File: src/driver/connection/mod.rs (hunk 2 above)
Comment (beer-psi) [reply src/driver/connection/mod.rs:384]: I think there were already other `.expect`s on channel ID already so I just followed them. Not entirely sure why it wasn't just required then either.

https://github.com/serenity-rs/songbird/blob/18c282e6768c61f54c1c0b31136f8f6156aaf9b9/src/info.rs#L34-L41

File: src/driver/tasks/ws.rs (hunk 3 above)
Comment (beer-psi) [reply src/driver/tasks/ws.rs:59]: I think it was originally a Tokio RWLock because the lock was held over an await point, but a lot of things shifted since then and looks like that isn't the case anymore.

File: src/driver/connection/mod.rs (hunk 2 above)
Comment (tazz4843) [reply src/driver/connection/mod.rs:384]: Let’s get this PR in and I can follow up with one that changes the type later.

**Review by tazz4843 — APPROVED** [review]

**Review by Erk- — APPROVED** [review]

**Review by GnomedDev — APPROVED** [review]
