### PR TITLE
Impl StdError

### LINKED ISSUE #72: Impl std::error::Error for songbird error types
This requires that every error impl Display.

### PR DESCRIPTION
**Pull request by vilgotf**
Closes #72

Most errors seem to already impl std::error::Error so this was a smaller change than expected.

### CODE REVIEW

File: src/input/error.rs [hunk 1]
```diff
@@ -68,6 +69,48 @@ impl From<OpusError> for Error {
...
+            Error::Streamcatcher(e) => write!(f, "{}", e),
+            Error::YouTubeDlProcessing(_) => write!(f, "Processing JSON from youtube-dl failed"),
+            Error::YouTubeDlRun(_) => write!(f, "youtube-dl encountered an error"),
+            Error::YouTubeDlUrl(_) => write!(f, "Missing url field in JSON"),
+        }
+    }
+}
+
+impl StdError for Error {
+    fn cause(&self) -> Option<&dyn StdError> {
```
Comment (FelixMcFelix) [inline src/input/error.rs]: It looks like `cause` is deprecated: could you please change this to `fn source`?

File: src/input/error.rs [hunk 2]
```diff
@@ -86,6 +129,30 @@ pub enum DcaError {
...
+            DcaError::InvalidHeader => write!(f, "Invalid DCA JSON header"),
+            DcaError::InvalidMetadata(e) => write!(f, "{}", e),
+            DcaError::InvalidSize(e) => write!(f, "Invalid metadata block size: {}", e),
+            DcaError::Opus(e) => write!(f, "{}", e),
+        }
+    }
+}
+
+impl StdError for DcaError {
+    fn cause(&self) -> Option<&dyn StdError> {
```
Comment (FelixMcFelix) [inline src/input/error.rs]: Same as above.

**Review by FelixMcFelix — CHANGES_REQUESTED** [review]
Thanks very much; I tried to get in a baseline `impl Error` for most structs, but it's clear that some slipped through the gaps.

Just needs some function prototypes changed, as `Error::cause` is now deprecated.

File: src/input/error.rs (hunk 1 above)
Comment (vilgotf) [reply src/input/error.rs]: Ah how awkward, I confused the two 😅

**Comment by vilgotf** [comment]
Should I squash or will you?

**Review by FelixMcFelix — APPROVED** [review]
LGTM; thanks! I'll squash it here.
